import React from "react";
import { ClientWithRevenueAndDamage } from "../../@types/db-entities";
import {
  BarChart,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  Bar
} from "recharts";
import ResponsiveFix from "../ResponsiveFix";
import { schemeCategory10 } from "d3-scale-chromatic";

function ClientsBarChart( {clients} : {clients: ClientWithRevenueAndDamage[]}) {
  return (
    <ResponsiveFix width="100%" height="100%" >
      <BarChart
        width={500}
        height={300}
        data={clients}
        margin={{
          top: 5,
          right: 30,
          left: 20,
        }}
        aria-label="revenue and damage generated by each client"
      >
        <CartesianGrid strokeDasharray="3 3" />
        <YAxis type="number" />
        <XAxis name="username" dataKey="user.username" type="category"  />
        <Tooltip />
        <Legend role="presentation" />
        <Bar dataKey="totalRevenue" name="revenue" barSize={20} fill={schemeCategory10[2]} />
        <Bar dataKey="totalDamage" name="damage" barSize={20} fill={schemeCategory10[3]} />
      </BarChart>
    </ResponsiveFix>
  );
}

export default ClientsBarChart