POST  http://localhost:8000/loginDashboard
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

###
GET  http://localhost:8000/users/User1/rentals
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXIiOnsiX2lkIjoiVXNlcjEiLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwibG95YWx0eVBvaW50cyI6MCwiZmF2Q2F0ZWdvcmllcyI6W10sImZhdkl0ZW1zSWQiOltdLCJyb2xlIjoiZnVuemlvbmFyaW8iLCJyZW50YWxzIjpbIlJlbnRhbDEiLCJSZW50YWwyIl0sInJldmlld3MiOltdLCJsYXN0VmlzaXQiOiIyMDIxLTExLTIwVDE1OjMzOjEyLjUyNloifSwiaWF0IjoxNjM3NDI0NjE2fQ.FB-6I8GkxgekEMn9hdYnEBjGzSLceor0TJhYYJek_aA

###
GET  http://localhost:8000/users/clients
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXIiOnsiX2lkIjoiVXNlcjEiLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwibG95YWx0eVBvaW50cyI6MCwiZmF2Q2F0ZWdvcmllcyI6W10sImZhdkl0ZW1zSWQiOltdLCJyb2xlIjoiZnVuemlvbmFyaW8iLCJyZW50YWxzIjpbIlJlbnRhbDEiLCJSZW50YWwyIl0sInJldmlld3MiOltdLCJsYXN0VmlzaXQiOiIyMDIxLTExLTIwVDE1OjMzOjEyLjUyNloifSwiaWF0IjoxNjM3NDI0NjE2fQ.FB-6I8GkxgekEMn9hdYnEBjGzSLceor0TJhYYJek_aA


###
GET  http://localhost:8000/users/employers/revenue
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXIiOnsiX2lkIjoiVXNlcjEiLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwibG95YWx0eVBvaW50cyI6MCwiZmF2Q2F0ZWdvcmllcyI6W10sImZhdkl0ZW1zSWQiOltdLCJyb2xlIjoiZnVuemlvbmFyaW8iLCJyZW50YWxzIjpbIlJlbnRhbDEiLCJSZW50YWwyIl0sInJldmlld3MiOltdLCJsYXN0VmlzaXQiOiIyMDIxLTExLTIwVDE1OjMzOjEyLjUyNloifSwiaWF0IjoxNjM3NDI0NjE2fQ.FB-6I8GkxgekEMn9hdYnEBjGzSLceor0TJhYYJek_aA


###
GET http://localhost:8000/users/clients/revenue
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXIiOnsiX2lkIjoiVXNlcjEiLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwibG95YWx0eVBvaW50cyI6MCwiZmF2Q2F0ZWdvcmllcyI6W10sImZhdkl0ZW1zSWQiOltdLCJyb2xlIjoiZnVuemlvbmFyaW8iLCJyZW50YWxzIjpbIlJlbnRhbDEiLCJSZW50YWwyIl0sInJldmlld3MiOltdLCJsYXN0VmlzaXQiOiIyMDIxLTExLTIwVDE1OjMzOjEyLjUyNloifSwiaWF0IjoxNjM3NDI0NjE2fQ.FB-6I8GkxgekEMn9hdYnEBjGzSLceor0TJhYYJek_aA

###
GET  http://localhost:8000/reviews
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXIiOnsiX2lkIjoiVXNlcjEiLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwibG95YWx0eVBvaW50cyI6MCwiZmF2Q2F0ZWdvcmllcyI6W10sImZhdkl0ZW1zSWQiOltdLCJyb2xlIjoiZnVuemlvbmFyaW8iLCJyZW50YWxzIjpbIlJlbnRhbDEiLCJSZW50YWwyIl0sInJldmlld3MiOltdLCJsYXN0VmlzaXQiOiIyMDIxLTExLTIwVDE1OjMzOjEyLjUyNloifSwiaWF0IjoxNjM3NDI0NjE2fQ.FB-6I8GkxgekEMn9hdYnEBjGzSLceor0TJhYYJek_aA

###
GET  http://localhost:8000/rentals
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoidXNlciIsInVzZXIiOnsiX2lkIjoiVXNlcjEiLCJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwic3VybmFtZSI6ImFkbWluIiwibG95YWx0eVBvaW50cyI6MCwiZmF2Q2F0ZWdvcmllcyI6W10sImZhdkl0ZW1zSWQiOltdLCJyb2xlIjoiZnVuemlvbmFyaW8iLCJyZW50YWxzIjpbIlJlbnRhbDEiLCJSZW50YWwyIl0sInJldmlld3MiOltdLCJsYXN0VmlzaXQiOiIyMDIxLTExLTIwVDE1OjMzOjEyLjUyNloifSwiaWF0IjoxNjM3NDI0NjE2fQ.FB-6I8GkxgekEMn9hdYnEBjGzSLceor0TJhYYJek_aA
